### ISSUE TITLE
A bucket name is needed to use Cloud Storage Error

### ISSUE THREAD

**Issue by sdan** [eashish93/imgsquash#2]
I copied my .env file to the root and /api/ folder to get an error saying:
 
```
/Users/surya/Documents/imgsquash/api/node_modules/@google-cloud/storage/build/src/storage.js:132
            throw new Error('A bucket name is needed to use Cloud Storage.');
                  ^
Error: A bucket name is needed to use Cloud Storage.
    at Storage.bucket (/Users/surya/Documents/imgsquash/api/node_modules/@google-cloud/storage/build/src/storage.js:132:19)
    at Object../src/ctrls/image.js (/Users/surya/Documents/imgsquash/api/build/webpack:/src/ctrls/image.js:20:25)
    at __webpack_require__ (/Users/surya/Documents/imgsquash/api/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/ctrls/index.js (/Users/surya/Documents/imgsquash/api/build/webpack:/src/ctrls/index.js:1:29)
    at __webpack_require__ (/Users/surya/Documents/imgsquash/api/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/routes.js (/Users/surya/Documents/imgsquash/api/build/webpack:/src/routes.js:3:27)
    at __webpack_require__ (/Users/surya/Documents/imgsquash/api/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/index.js (/Users/surya/Documents/imgsquash/api/build/webpack:/src/index.js:8:23)
    at __webpack_require__ (/Users/surya/Documents/imgsquash/api/build/webpack:/webpack/bootstrap:19:1)
    at Object.0 (/Users/surya/Documents/imgsquash/api/build/main.js:1083:18)
```

My env file looks like this:
```
API_VERSION : 1
GC_STORAGE : data.suryad.com
DL_BASE_URL : data.suryad.com/1/dl
```
My GCS name is `data.suryad.com` but am not sure what you mean by `API_URL`. Not sure if my setup of my env file is wrong, but I cannot do npm run dev and get it running on localhost:3000.

**Comment by eashish93** [comment]
You're probably getting this error because you've either not set `GOOGLE_APPLICATION_CREDENTIALS` env variable to google cloud service file or is not authenticated to right project. The easiest way to check from terminal is to use `gcloud config list` or `gcloud auth list` or follow this guide to list buckets: https://cloud.google.com/storage/docs/listing-buckets#storage-list-buckets-nodejs

**Comment by sdan** [comment]
Here is my output for `gcloud config list`
```
[compute]
region = us-west1
zone = us-west1-b
[core]
account = *redacted*
disable_usage_reporting = True
project = *redacted*

Your active configuration is: [default]
```
and running `gsutil ls` gives me
`gs://data.suryad.com/`.

I still can't get it to work. What should `DL_BASE_URL` be equal to in my case?

**Comment by eashish93** [comment]
`DL_BASE_URL` should be `<your-api-url>/1/dl`. In dev, it should be `localhost:3000`. But that error is not due to this variable. Env variables should be set like this ([see here](https://www.npmjs.com/package/dotenv))
```.env
API_VERSION=1
GC_STORAGE=data.suryad.com
DL_BASE_URL=http://localhost:3000/1/dl
```

**Comment by sdan** [comment]
Great. The local server runs yet I get this when I go to `http://localhost:3000`:
`{"code":404,"success":false,"type":"not-found","message":"The requested resource (or url) could not be found."}`
What could be the cause of this?

**Comment by eashish93** [comment]
You're running api service which expose some endpoints written in readme. For frontend you need to run dev server from `front` folder.
